services:
  syndic-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "8888:18888"
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "syndic.apphost-39d155828d-postgres-data"
        read_only: false
    networks:
      - "aspire"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U postgres -d reader"
      interval: "10s"
      timeout: "10s"
      retries: 5
      start_period: "30s"
  syndic-worker:
    image: "${SYNDIC_WORKER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__syndic-db: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=reader"
      SYNDIC-DB_HOST: "postgres"
      SYNDIC-DB_PORT: "5432"
      SYNDIC-DB_USERNAME: "postgres"
      SYNDIC-DB_PASSWORD: "${POSTGRES_PASSWORD}"
      SYNDIC-DB_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/reader"
      SYNDIC-DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/reader"
      SYNDIC-DB_DATABASE: "reader"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://syndic-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "syndic-worker"
    depends_on:
      postgres:
        condition: "service_healthy"
    networks:
      - "aspire"
  syndic-api:
    image: "${SYNDIC_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${SYNDIC_API_PORT}"
      ConnectionStrings__syndic-db: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=reader"
      SYNDIC-DB_HOST: "postgres"
      SYNDIC-DB_PORT: "5432"
      SYNDIC-DB_USERNAME: "postgres"
      SYNDIC-DB_PASSWORD: "${POSTGRES_PASSWORD}"
      SYNDIC-DB_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/reader"
      SYNDIC-DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/reader"
      SYNDIC-DB_DATABASE: "reader"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://syndic-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "syndic-api"
    expose:
      - "${SYNDIC_API_PORT}"
    depends_on:
      postgres:
        condition: "service_started"
      syndic-worker:
        condition: "service_completed_successfully"
    networks:
      - "aspire"
  syndic-frontend:
    image: "${SYNDIC_FRONTEND_IMAGE}"
    environment:
      NODE_ENV: "production"
      SYNDIC-API_HTTP: "http://syndic-api:${SYNDIC_API_PORT}"
      services__syndic-api__http__0: "http://syndic-api:${SYNDIC_API_PORT}"
      SYNDIC-API_HTTPS: "https://syndic-api:${SYNDIC_API_PORT}"
      PORT: "8000"
      AUTH_AUTHENTIK_ID: "${SYNDIC_FRONTEND_AUTHENTIK_CLIENT_ID}"
      AUTH_AUTHENTIK_CLIENT_SECRET: "${SYNDIC_FRONTEND_AUTHENTIK_CLIENT_SECRET}"
      AUTH_AUTHENTIK_ISSUER: "${AUTHENTIK_ISSUER_URL}"
      AUTH_SECRET: "${AUTHJS_SECRET}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://syndic-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "syndic-frontend"
    ports:
      - "8080:8000"
    depends_on:
      syndic-api:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  syndic.apphost-39d155828d-postgres-data:
    driver: "local"
